services:
  db:
    image: "postgres:latest"
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${PLANNER_DB_USER}
      POSTGRES_DB: ${PLANNER_DB_NAME}
      POSTGRES_PASSWORD: ${PLANNER_DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - 8080:8080
    environment:
      PLANNER_DB_NAME: ${PLANNER_DB_NAME}
      PLANNER_DB_USER: ${PLANNER_DB_USER}
      PLANNER_DB_PASSWORD: ${PLANNER_DB_PASSWORD}
      PLANNER_DB_PORT: ${PLANNER_DB_PORT:-5432}
      PLANNER_DB_HOST: ${PLANNER_DB_HOST_DOCKER:-db}
    depends_on:
      - db

volumes:
  db:
    driver: local